backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

  # These lines should *not* be indented
media_folder: "public" # Media files will be stored in the repo under static/images/uploads
public_folder: "./" # The src attribute for uploaded media will begin with /images/uploads

publish_mode: editorial_workflow
site_url: https://paulies-astro-blog.netlify.app

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {
          label: "Publish",
          name: "isPublish",
          widget: "boolean",
          default: true,
        }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
